steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'REACT_APP_API_KEY=${_API_KEY}'
  - '-t'
  - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image'
  - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}'
  - '--region'
  - '${_DEPLOY_REGION}'
  - '--platform'
  - '${_PLATFORM}'
  - '--no-allow-unauthenticated'
  - '--project'
  - '${_AR_PROJECT_ID}'

images:
- '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}'

substitutions:
  _API_KEY: ''

options:
  logging: CLOUD_LOGGING_ONLY
